/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package scc_project;

/**
 *
 * @author Gonçalo
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    Simulador simulator;
    public Interface(Simulador simulator) {
        initComponents();
        Spinner1.setVisible(false);
        Spinner2.setVisible(false);
        Spinner3.setVisible(false);
        this.simulator=simulator;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSpinner1 = new javax.swing.JSpinner();
        Clients = new javax.swing.JTextField();
        Time = new javax.swing.JTextField();
        runClients = new javax.swing.JButton();
        runTime = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Display = new javax.swing.JTextArea();
        exit = new javax.swing.JButton();
        ComboBox = new javax.swing.JComboBox();
        Spinner1 = new javax.swing.JSpinner();
        Spinner2 = new javax.swing.JSpinner();
        Spinner3 = new javax.swing.JSpinner();
        aviso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        Clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientsActionPerformed(evt);
            }
        });

        runClients.setText("Número de Clientes");
        runClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runClientsActionPerformed(evt);
            }
        });

        runTime.setText("Tempo");
        runTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runTimeActionPerformed(evt);
            }
        });

        Display.setColumns(20);
        Display.setRows(5);
        jScrollPane1.setViewportView(Display);

        exit.setText("Sair");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cenário 1", "Cenário 2", "Cenário 3" }));
        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });

        Spinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        Spinner2.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        Spinner3.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(aviso))
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(runClients, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Time)
                                    .addComponent(Clients)
                                    .addComponent(ComboBox, 0, 178, Short.MAX_VALUE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(runTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(33, 33, 33))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(Spinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Spinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(Spinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clients, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(runClients, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(runTime, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aviso)
                        .addGap(9, 9, 9)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void runClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runClientsActionPerformed
        int clients;
        try{

                 clients= Integer.parseInt(Clients.getText());
               
       
       }
            catch(NumberFormatException e)
            {
                aviso.setText("Insira um número de clientes correto");
                return;
            }
        if(clients<1){
            aviso.setText("Insira um número de clientes correto");
            return;
       }

        
        
        if(ComboBox.getSelectedIndex()==0){
        
        
        
            Display.setText(simulator.executa(Integer.parseInt(Clients.getText()),1, 1,2,1,1));
            aviso.setText("");
       }
        else if(ComboBox.getSelectedIndex()==1){
           Display.setText(simulator.executa(Integer.parseInt(Clients.getText()),1, 1,(Integer)(Spinner1.getValue()),(Integer)(Spinner2.getValue()),(Integer)(Spinner3.getValue())));
            aviso.setText("");
       }
        else{
            Display.setText(simulator.executa(Integer.parseInt(Clients.getText()),1, 2 , 4, 0, 0));
            aviso.setText("");
        }
       
    }//GEN-LAST:event_runClientsActionPerformed

    private void runTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runTimeActionPerformed
       int time;
        try{

                 time= Integer.parseInt(Time.getText());
               
       
       }
            catch(NumberFormatException e)
            {
                aviso.setText("Insira um número de segundos correto");
                return;
            }
        if(time<1){
            aviso.setText("Insira um número de segundos correto");
       }
        
        else if(ComboBox.getSelectedIndex()==0){
        
            Display.setText(simulator.executa(Integer.parseInt(Time.getText()),2, 1,2,1,1));
            aviso.setText("");
       }
       else if(ComboBox.getSelectedIndex()==1){
           Display.setText(simulator.executa(Integer.parseInt(Time.getText()),2, 1,(Integer)(Spinner1.getValue()),(Integer)(Spinner2.getValue()),(Integer)(Spinner3.getValue())));
            aviso.setText("");
       }
       else{
           Display.setText(simulator.executa(Integer.parseInt(Time.getText()),2, 2, 4,0,0));
            aviso.setText("");
       }
       
    }//GEN-LAST:event_runTimeActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void ClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientsActionPerformed

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        if(ComboBox.getSelectedIndex()==0){
            Spinner1.setVisible(false);
            Spinner2.setVisible(false);
            Spinner3.setVisible(false);
        }
        else if(ComboBox.getSelectedIndex()==1){
            Spinner1.setVisible(true);
            Spinner2.setVisible(true);
            Spinner3.setVisible(true); 
        }
        else if(ComboBox.getSelectedIndex()==2){
            Spinner1.setVisible(false);
            Spinner2.setVisible(false);
            Spinner3.setVisible(false);
        }
    }//GEN-LAST:event_ComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Clients;
    private javax.swing.JComboBox ComboBox;
    private javax.swing.JTextArea Display;
    private javax.swing.JSpinner Spinner1;
    private javax.swing.JSpinner Spinner2;
    private javax.swing.JSpinner Spinner3;
    private javax.swing.JTextField Time;
    private javax.swing.JLabel aviso;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton runClients;
    private javax.swing.JButton runTime;
    // End of variables declaration//GEN-END:variables
}
